name: Build and Package Electron App

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: phips28/gh-action-bump-version@master
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          tag-prefix: ''
          minor: true

  build:
    needs: version-bump
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run dist --publish=never
      - uses: actions/upload-artifact@v2
        with:
          name: windows-exe-artifact
          path: dist/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: windows-exe-artifact
          path: dist
      - run: git fetch --tags
      - run: echo "RELEASE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          tag_name: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GH_TOKEN }}
